services:
    next-app:
        build: .
        container_name: nextjs_app
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
        env_file:
            - .env
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:3000']
            interval: 30s
            timeout: 10s
            retries: 5
        command: npm start
